language: go

go:
  - "1.15"

script:
  - go test -v ./...
  - go build main.go

before_deploy:
  - ls -al
deploy:
  provider: releases
  api_key: $TOKEN
  file: main
  skip_cleanup: true
  draft: true